name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Init/Update submodules
      run: git submodule update --init
    
    - name: Install dependencies
      run: sudo apt-get install -y pandoc make texlive-xetex texlive-lang-cjk fonts-nanum

    - name: Build PDF
      run: make

    - name: Change PDF name
      run: mv main.pdf C-Study-Guideline.pdf

    - name: Uplaod PDF 
      uses: actions/upload-artifact@v4
      with:
        name: C-Study-Guideline.pdf
        path: C-Study-Guideline.pdf
