name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Init/Update submodules
      run: git submodule update --init
    
    - name: Install dependencies
      run: sudo apt-get install -y pandoc make texlive-xetex texlive-lang-cjk fonts-nanum

    - name: Build PDF
      run: make

    - name: Change PDF name
      run: mv main.pdf C-Study-Guideline.pdf

    - name: Uplaod PDF as artifact
      uses: actions/upload-artifact@v4
      with:
        name: C-Study-Guideline.pdf
        path: C-Study-Guideline.pdf

    - name: Get Today
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M')"
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
      with:
        tag_name: tag-${{ steps.date.outputs.date }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        
    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: C-Study-Guideline.pdf
        asset_name: C-Study-Guideline.pdf
        asset_content_type: application/pdf
